-- Law Market — seed data
--
-- Generated from data/*.ts by scripts/generate-seed.mjs.
-- Safe to re-run: every insert upserts on its natural key.

-- Categories -------------------------------------------------------------
insert into public.categories (slug, name_en, name_ka, icon, sort_order) values
  ('business', 'Business & Corporate', 'ბიზნესი და კორპორატიული სამართალი', 'briefcase', 0),
  ('family', 'Family Law', 'საოჯახო სამართალი', 'users', 1),
  ('immigration', 'Immigration', 'იმიგრაცია', 'globe', 2),
  ('real-estate', 'Real Estate', 'უძრავი ქონება', 'home', 3),
  ('contracts', 'Contracts & Agreements', 'ხელშეკრულებები და შეთანხმებები', 'file-text', 4),
  ('tax', 'Tax & Finance', 'გადასახადები და ფინანსები', 'landmark', 5),
  ('criminal', 'Criminal Defense', 'სისხლის სამართალი', 'shield', 6),
  ('notary', 'Notary Services', 'სანოტარო მომსახურება', 'stamp', 7)
on conflict (slug) do update set
  name_en = excluded.name_en, name_ka = excluded.name_ka, icon = excluded.icon, sort_order = excluded.sort_order;

-- Lawyers ----------------------------------------------------------------
insert into public.lawyers (slug, name, initials, avatar_color, photo_url, headline_en, headline_ka, bio_en, bio_ka, city, languages, years_experience, verified, sort_order) values
  ('nino-beridze', 'Nino Beridze', 'NB', '#6b1423', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=500&fit=crop&crop=faces', 'Business & Corporate Lawyer', 'ბიზნესის და კორპორატიული სამართლის იურისტი', 'Nino has spent over a decade helping founders register companies, structure investments, and protect their brands across Georgia. She is known for explaining complex corporate matters in plain language.', 'ნინო ათ წელზე მეტია ეხმარება დამფუძნებლებს კომპანიების რეგისტრაციაში, ინვესტიციების სტრუქტურირებასა და ბრენდის დაცვაში საქართველოში. იგი ცნობილია რთული კორპორატიული საკითხების მარტივად ახსნით.', 'Tbilisi', array['Georgian', 'English', 'Russian']::text[], 11, true, 0),
  ('giorgi-abashidze', 'Giorgi Abashidze', 'GA', '#1c1210', 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=500&fit=crop&crop=faces', 'Family Law Attorney', 'საოჯახო სამართლის ადვოკატი', 'Giorgi guides families through divorce, custody, and inheritance matters with a calm, practical approach, focused on protecting his clients and their children.', 'გიორგი ოჯახებს უძღვება განქორწინების, მეურვეობისა და მემკვიდრეობის საკითხებში მშვიდი და პრაქტიკული მიდგომით, კლიენტებისა და მათი შვილების დაცვაზე ორიენტირებით.', 'Tbilisi', array['Georgian', 'English']::text[], 9, true, 1),
  ('ana-kapanadze', 'Ana Kapanadze', 'AK', '#8a6d3b', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=500&fit=crop&crop=faces', 'Immigration Lawyer', 'საიმიგრაციო იურისტი', 'Ana specializes in residence permits, visas, and citizenship applications for foreigners relocating to Georgia, with particular experience supporting remote workers and small business owners.', 'ანა სპეციალიზირებულია ბინადრობის ნებართვების, ვიზებისა და მოქალაქეობის განაცხადებში საქართველოში გადმოსახლებული უცხოელებისთვის, განსაკუთრებული გამოცდილებით დისტანციური მუშაკებისა და მცირე ბიზნესის მფლობელების მხარდაჭერაში.', 'Batumi', array['Georgian', 'English', 'Turkish']::text[], 7, true, 2),
  ('levan-tsereteli', 'Levan Tsereteli', 'LT', '#6b1423', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=500&fit=crop&crop=faces', 'Real Estate Lawyer', 'უძრავი ქონების იურისტი', 'Levan reviews and negotiates property purchase agreements, leases, and landlord-tenant disputes, helping clients avoid costly mistakes before signing.', 'ლევანი ამოწმებს და აწარმოებს მოლაპარაკებებს უძრავი ქონების ნასყიდობის ხელშეკრულებებზე, იჯარებსა და მეიჯარე-მოიჯარეს შორის დავებზე, ეხმარება კლიენტებს თავიდან აიცილონ ძვირადღირებული შეცდომები ხელმოწერამდე.', 'Tbilisi', array['Georgian', 'English']::text[], 13, true, 3),
  ('mariam-chkheidze', 'Mariam Chkheidze', 'MC', '#1c1210', 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=400&h=500&fit=crop&crop=faces', 'Contracts Attorney', 'სახელშეკრულებო სამართლის ადვოკატი', 'Mariam drafts and reviews employment, service, and partnership agreements for small businesses, making sure contracts are clear and enforceable for both sides.', 'მარიამი ადგენს და ამოწმებს შრომით, სამომსახურეო და პარტნიორულ ხელშეკრულებებს მცირე ბიზნესებისთვის და უზრუნველყოფს, რომ ხელშეკრულებები ორივე მხარისთვის იყოს ნათელი და აღსრულებადი.', 'Kutaisi', array['Georgian', 'English', 'Russian']::text[], 8, true, 4),
  ('david-lomidze', 'David Lomidze', 'DL', '#8a6d3b', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=500&fit=crop&crop=faces', 'Tax & Finance Lawyer', 'საგადასახადო და საფინანსო იურისტი', 'David advises freelancers and small businesses on Georgia''s small business tax status, international taxation, and financial compliance.', 'დავითი კონსულტაციას უწევს ფრილანსერებსა და მცირე ბიზნესებს საქართველოს მცირე ბიზნესის საგადასახადო სტატუსზე, საერთაშორისო დაბეგვრასა და ფინანსურ შესაბამისობაზე.', 'Tbilisi', array['Georgian', 'English']::text[], 10, true, 5),
  ('ketevan-japaridze', 'Ketevan Japaridze', 'KJ', '#6b1423', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=500&fit=crop&crop=faces', 'Criminal Defense Attorney', 'სისხლის სამართლის ადვოკატი', 'Ketevan defends clients at every stage of criminal proceedings, from initial questioning through trial, with a strong record in procedural defense.', 'ქეთევანი იცავს კლიენტებს სისხლის სამართლის პროცესის ყველა ეტაპზე, პირველადი დაკითხვიდან სასამართლო პროცესამდე, საპროცესო დაცვაში ძლიერი გამოცდილებით.', 'Tbilisi', array['Georgian', 'Russian']::text[], 15, true, 6),
  ('irakli-mchedlishvili', 'Irakli Mchedlishvili', 'IM', '#1c1210', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop&crop=faces', 'Notary Services', 'სანოტარო მომსახურება', 'Irakli provides notarization and certified translation of documents for individuals and businesses, including documents used abroad.', 'ირაკლი უზრუნველყოფს დოკუმენტების ნოტარიულ დამოწმებასა და დამოწმებულ თარგმანს ფიზიკური და იურიდიული პირებისთვის, მათ შორის საზღვარგარეთ გამოსაყენებელი დოკუმენტებისთვის.', 'Batumi', array['Georgian', 'English', 'Turkish']::text[], 12, true, 7)
on conflict (slug) do update set
  name = excluded.name, initials = excluded.initials, avatar_color = excluded.avatar_color,
  photo_url = excluded.photo_url, headline_en = excluded.headline_en, headline_ka = excluded.headline_ka,
  bio_en = excluded.bio_en, bio_ka = excluded.bio_ka, city = excluded.city, languages = excluded.languages,
  years_experience = excluded.years_experience, verified = excluded.verified, sort_order = excluded.sort_order;

-- Practice areas ---------------------------------------------------------
insert into public.lawyer_practice_areas (lawyer_id, category_id) values
  ((select id from public.lawyers where slug = 'nino-beridze'), (select id from public.categories where slug = 'business')),
  ((select id from public.lawyers where slug = 'nino-beridze'), (select id from public.categories where slug = 'contracts')),
  ((select id from public.lawyers where slug = 'giorgi-abashidze'), (select id from public.categories where slug = 'family')),
  ((select id from public.lawyers where slug = 'ana-kapanadze'), (select id from public.categories where slug = 'immigration')),
  ((select id from public.lawyers where slug = 'levan-tsereteli'), (select id from public.categories where slug = 'real-estate')),
  ((select id from public.lawyers where slug = 'mariam-chkheidze'), (select id from public.categories where slug = 'contracts')),
  ((select id from public.lawyers where slug = 'mariam-chkheidze'), (select id from public.categories where slug = 'business')),
  ((select id from public.lawyers where slug = 'david-lomidze'), (select id from public.categories where slug = 'tax')),
  ((select id from public.lawyers where slug = 'ketevan-japaridze'), (select id from public.categories where slug = 'criminal')),
  ((select id from public.lawyers where slug = 'irakli-mchedlishvili'), (select id from public.categories where slug = 'notary'))
on conflict do nothing;

-- Services ---------------------------------------------------------------
insert into public.services (slug, category_id, lawyer_id, title_en, title_ka, description_en, description_ka, price, currency, duration_minutes, popular, includes_en, includes_ka, faq_en, faq_ka, sort_order) values
  ('llc-formation', (select id from public.categories where slug = 'business'), (select id from public.lawyers where slug = 'nino-beridze'), 'LLC Formation', 'შპს-ს დაფუძნება', 'Full company registration service: name reservation, founding documents, and registration with the Public Registry, so your LLC is ready to operate.', 'კომპანიის სრული რეგისტრაციის სერვისი: სახელის დაჯავშნა, დამფუძნებელი დოკუმენტები და რეგისტრაცია საჯარო რეესტრში, რათა თქვენი შპს მზად იყოს საქმიანობისთვის.', 800, 'GEL', null, true, array['Company name availability check', 'Founding documents drafted and filed', 'Public Registry registration', 'Bank-ready company extract']::text[], array['კომპანიის სახელის ხელმისაწვდომობის შემოწმება', 'დამფუძნებელი დოკუმენტების მომზადება და წარდგენა', 'საჯარო რეესტრში რეგისტრაცია', 'ბანკისთვის გამოსაყენებელი ამონაწერი']::text[], '[{"q":"How long does LLC registration take?","a":"Most registrations complete within 5–10 business days after documents are submitted."},{"q":"Do I need to visit in person?","a":"In most cases, registration can be handled remotely with a power of attorney."}]'::jsonb, '[{"q":"რამდენ ხანში დასრულდება შპს-ს რეგისტრაცია?","a":"დოკუმენტების წარდგენის შემდეგ რეგისტრაცია ჩვეულებრივ 5–10 სამუშაო დღეში სრულდება."},{"q":"საჭიროა პირადად მოსვლა?","a":"უმეტეს შემთხვევაში რეგისტრაცია დისტანციურადაც შეიძლება, მინდობილობის საფუძველზე."}]'::jsonb, 0),
  ('contract-review', (select id from public.categories where slug = 'contracts'), (select id from public.lawyers where slug = 'mariam-chkheidze'), 'Contract Review', 'ხელშეკრულების შემოწმება', 'A thorough review of any contract before you sign, with plain-language notes on risks, unusual clauses, and suggested changes.', 'ნებისმიერი ხელშეკრულების საფუძვლიანი შემოწმება ხელმოწერამდე, რისკებზე, უჩვეულო პუნქტებზე და შესაძლო ცვლილებებზე გასაგებ ენაზე შენიშვნებით.', 350, 'GEL', 60, true, array['Full clause-by-clause review', 'Risk summary in plain language', 'Suggested edits and redlines', '30-minute follow-up call']::text[], array['პუნქტ-პუნქტოვანი სრული შემოწმება', 'რისკების მოკლე შეჯამება გასაგებ ენაზე', 'შემოთავაზებული ცვლილებები და შენიშვნები', '30-წუთიანი დამატებითი კონსულტაცია']::text[], '[{"q":"What types of contracts can you review?","a":"Employment, service, lease, partnership, and commercial agreements of any length."},{"q":"How fast is the turnaround?","a":"Standard review is delivered within 2 business days of receiving the document."}]'::jsonb, '[{"q":"რა ტიპის ხელშეკრულებებს ამოწმებთ?","a":"შრომით, სამომსახურეო, იჯარის, პარტნიორულ და სავაჭრო ხელშეკრულებებს ნებისმიერი მოცულობით."},{"q":"რამდენ ხანში მივიღებ შედეგს?","a":"სტანდარტული შემოწმება დოკუმენტის მიღებიდან 2 სამუშაო დღეში ეგზავნება."}]'::jsonb, 1),
  ('divorce-filing', (select id from public.categories where slug = 'family'), (select id from public.lawyers where slug = 'giorgi-abashidze'), 'Divorce Filing', 'განქორწინების საქმის წარმოება', 'End-to-end support for filing an uncontested divorce, including document preparation and court filing, handled with care and confidentiality.', 'სრული მხარდაჭერა შეუთანხმებელი განქორწინების საქმის წარსადგენად, დოკუმენტების მომზადებისა და სასამართლოში წარდგენის ჩათვლით, ყურადღებითა და კონფიდენციალურობით.', 900, 'GEL', null, true, array['Initial consultation and case assessment', 'All required court documents prepared', 'Filing with the relevant court', 'Status updates until judgment']::text[], array['საწყისი კონსულტაცია და საქმის შეფასება', 'სასამართლოსთვის საჭირო ყველა დოკუმენტის მომზადება', 'შესაბამის სასამართლოში წარდგენა', 'გადაწყვეტილებამდე სტატუსის განახლებები']::text[], '[{"q":"Is this for contested divorces?","a":"This service covers uncontested divorces. Contested cases require a separate consultation."},{"q":"How long does the process take?","a":"Timelines vary by court, but uncontested cases typically resolve in 2–4 months."}]'::jsonb, '[{"q":"ეს შეუთანხმებელი განქორწინებისთვისაა?","a":"ეს სერვისი მოიცავს შეთანხმებით განქორწინებას. დავიანი შემთხვევები ცალკე კონსულტაციას საჭიროებს."},{"q":"რამდენ ხანს გრძელდება პროცესი?","a":"ვადები სასამართლოზეა დამოკიდებული, მაგრამ შეთანხმებით შემთხვევები ჩვეულებრივ 2–4 თვეში სრულდება."}]'::jsonb, 2),
  ('trademark-registration', (select id from public.categories where slug = 'business'), (select id from public.lawyers where slug = 'nino-beridze'), 'Trademark Registration', 'სასაქონლო ნიშნის რეგისტრაცია', 'Protect your brand name and logo with a full trademark search and registration application with the National Intellectual Property Center.', 'დაიცავით თქვენი ბრენდის სახელი და ლოგო სასაქონლო ნიშნის სრული ძიებითა და საქართველოს ინტელექტუალური საკუთრების ეროვნულ ცენტრში რეგისტრაციის განაცხადით.', 650, 'GEL', null, true, array['Trademark availability search', 'Application drafted and filed with Sakpatenti', 'Response to basic office actions', 'Registration certificate guidance']::text[], array['სასაქონლო ნიშნის ხელმისაწვდომობის ძიება', 'განაცხადის მომზადება და წარდგენა საქპატენტოში', 'საწყისი ოფისის მოთხოვნებზე პასუხი', 'რეგისტრაციის მოწმობის მიღების რჩევები']::text[], '[{"q":"How long does trademark registration take?","a":"The full process typically takes 8–12 months depending on examination."},{"q":"Can I register a logo and a name together?","a":"Yes — combined or separate applications can be filed depending on your brand strategy."}]'::jsonb, '[{"q":"რამდენ ხანში სრულდება სასაქონლო ნიშნის რეგისტრაცია?","a":"სრული პროცესი ჩვეულებრივ 8–12 თვეს გრძელდება განხილვის მიხედვით."},{"q":"შემიძლია ლოგოსა და სახელის ერთად რეგისტრაცია?","a":"დიახ — შესაძლებელია როგორც ერთიანი, ისე ცალკე განაცხადების წარდგენა."}]'::jsonb, 3),
  ('will-estate-planning', (select id from public.categories where slug = 'family'), (select id from public.lawyers where slug = 'giorgi-abashidze'), 'Will & Estate Planning', 'ანდერძი და მემკვიდრეობის დაგეგმვა', 'Draft a legally sound will that reflects your wishes and protects your family, with guidance on estate planning options.', 'შეადგინეთ იურიდიულად უზადო ანდერძი, რომელიც ასახავს თქვენს სურვილებს და იცავს თქვენს ოჯახს, მემკვიდრეობის დაგეგმვის ვარიანტებზე კონსულტაციით.', 600, 'GEL', null, true, array['Consultation on your wishes and assets', 'Will drafted to Georgian law standards', 'Notarization guidance', 'One round of revisions included']::text[], array['კონსულტაცია თქვენს სურვილებსა და აქტივებზე', 'ანდერძის შედგენა საქართველოს კანონმდებლობის მიხედვით', 'ნოტარიულად დამოწმების რჩევები', 'ერთი რევიზიის რაუნდი ჩართულია']::text[], '[{"q":"Is notarization included in the price?","a":"Notary fees are separate; we guide you through the process and required documents."},{"q":"Can this cover property abroad?","a":"We can address Georgian assets fully; foreign assets may need coordination with local counsel."}]'::jsonb, '[{"q":"ნოტარიუსის ფასი ფასში შედის?","a":"ნოტარიუსის საფასური ცალკეა; ჩვენ გიყვანთ პროცესში და საჭირო დოკუმენტებში."},{"q":"შეიძლება საზღვარგარეთის ქონების ჩართვა?","a":"საქართველოს აქტივებს სრულად ვაფარებთ; უცხოური აქტივები შეიძლება საჭიროებდეს ადგილობრივ იურისტს."}]'::jsonb, 4),
  ('visa-residence-permit-filing', (select id from public.categories where slug = 'immigration'), (select id from public.lawyers where slug = 'ana-kapanadze'), 'Visa & Residence Permit Filing', 'ვიზისა და ბინადრობის ნებართვის განაცხადი', 'Preparation and submission of your residence permit or visa application, including document checklists tailored to your situation.', 'თქვენი ბინადრობის ნებართვის ან ვიზის განაცხადის მომზადება და წარდგენა, თქვენს სიტუაციაზე მორგებული საბუთების ჩამონათვალის ჩათვლით.', 550, 'GEL', null, true, array['Eligibility assessment for your situation', 'Document checklist and preparation', 'Application filed with relevant authority', 'Follow-up until decision']::text[], array['თქვენს სიტუაციაზე უფლებამოსილების შეფასება', 'საბუთების ჩამონათვალი და მომზადება', 'განაცხადის წარდგენა შესაბამის ორგანოში', 'გადაწყვეტამდე თანაგზობა']::text[], '[{"q":"Which residence permits do you handle?","a":"Work, study, family reunification, and special-category permits for Georgia."},{"q":"Can you help if my application was rejected?","a":"Yes — we can review the decision and advise on appeal or reapplication options."}]'::jsonb, '[{"q":"რომელი ბინადრობის ნებართვებს ამზადებთ?","a":"სამუშაო, სწავლის, ოჯახის შეხვედრისა და სპეციალური კატეგორიის ნებართვებს საქართველოში."},{"q":"დამეხმარებით, თუ განაცხადი უარყოფილია?","a":"დიახ — გადაწყვეტილებას გავაანალიზებთ და გირჩევთ სააპელაციო ან ხელახალი განაცხადის ვარიანტებს."}]'::jsonb, 5),
  ('property-purchase-agreement-review', (select id from public.categories where slug = 'real-estate'), (select id from public.lawyers where slug = 'levan-tsereteli'), 'Property Purchase Agreement Review', 'უძრავი ქონების ნასყიდობის ხელშეკრულების შემოწმება', 'Independent review of a property purchase agreement to check ownership history, encumbrances, and contract terms before you buy.', 'უძრავი ქონების ნასყიდობის ხელშეკრულების დამოუკიდებელი შემოწმება საკუთრების ისტორიის, ტვირთის და ხელშეკრულების პირობების დასადგენად შეძენამდე.', 450, 'GEL', 90, false, '{}', '{}', '[]'::jsonb, '[]'::jsonb, 6),
  ('business-registration-consultation', (select id from public.categories where slug = 'business'), (select id from public.lawyers where slug = 'nino-beridze'), 'Business Registration Consultation', 'ბიზნესის რეგისტრაციის კონსულტაცია', 'A one-on-one session to choose the right business structure and understand the registration process before you commit.', 'პირადი კონსულტაცია სწორი ბიზნეს-სტრუქტურის შესარჩევად და რეგისტრაციის პროცესის გასაგებად გადაწყვეტილების მიღებამდე.', 200, 'GEL', 45, false, '{}', '{}', '[]'::jsonb, '[]'::jsonb, 7),
  ('child-custody-consultation', (select id from public.categories where slug = 'family'), (select id from public.lawyers where slug = 'giorgi-abashidze'), 'Child Custody Consultation', 'მეურვეობის საკითხზე კონსულტაცია', 'A confidential session to understand your rights and options in a custody matter, and what to expect from the process.', 'კონფიდენციალური კონსულტაცია მეურვეობის საკითხში თქვენი უფლებებისა და შესაძლებლობების გასაგებად და პროცესისგან მოსალოდნელის გასაცნობად.', 250, 'GEL', 45, false, '{}', '{}', '[]'::jsonb, '[]'::jsonb, 8),
  ('employment-contract-drafting', (select id from public.categories where slug = 'contracts'), (select id from public.lawyers where slug = 'mariam-chkheidze'), 'Employment Contract Drafting', 'შრომითი ხელშეკრულების შედგენა', 'A custom employment agreement drafted for your business, compliant with Georgian labor law and tailored to the role.', 'თქვენი ბიზნესისთვის მორგებული შრომითი ხელშეკრულების შედგენა, საქართველოს შრომის კანონმდებლობასთან შესაბამისობით.', 400, 'GEL', null, false, '{}', '{}', '[]'::jsonb, '[]'::jsonb, 9),
  ('tax-consultation-small-business', (select id from public.categories where slug = 'tax'), (select id from public.lawyers where slug = 'david-lomidze'), 'Tax Consultation for Small Business', 'საგადასახადო კონსულტაცია მცირე ბიზნესისთვის', 'Understand your tax obligations, including small business status eligibility, and get a clear plan for staying compliant.', 'გაიგეთ თქვენი საგადასახადო ვალდებულებები, მცირე ბიზნესის სტატუსის შესაბამისობის ჩათვლით, და მიიღეთ მკაფიო გეგმა შესაბამისობის შესანარჩუნებლად.', 300, 'GEL', 45, false, '{}', '{}', '[]'::jsonb, '[]'::jsonb, 10),
  ('criminal-defense-consultation', (select id from public.categories where slug = 'criminal'), (select id from public.lawyers where slug = 'ketevan-japaridze'), 'Criminal Defense Consultation', 'სისხლის სამართლის დაცვის კონსულტაცია', 'An urgent, confidential consultation to understand the charges against you and your immediate options and rights.', 'სასწრაფო, კონფიდენციალური კონსულტაცია თქვენს წინააღმდეგ წაყენებული ბრალდებისა და თქვენი უშუალო შესაძლებლობებისა და უფლებების გასაცნობად.', 350, 'GEL', 30, false, '{}', '{}', '[]'::jsonb, '[]'::jsonb, 11),
  ('notarized-document-translation', (select id from public.categories where slug = 'notary'), (select id from public.lawyers where slug = 'irakli-mchedlishvili'), 'Notarized Document Translation', 'დოკუმენტის ნოტარიულად დამოწმებული თარგმანი', 'Certified translation and notarization of personal or business documents for use in Georgia or abroad.', 'პირადი ან ბიზნეს დოკუმენტების დამოწმებული თარგმანი და ნოტარიული დამოწმება საქართველოში ან საზღვარგარეთ გამოსაყენებლად.', 150, 'GEL', null, false, '{}', '{}', '[]'::jsonb, '[]'::jsonb, 12),
  ('landlord-tenant-dispute-resolution', (select id from public.categories where slug = 'real-estate'), (select id from public.lawyers where slug = 'levan-tsereteli'), 'Landlord-Tenant Dispute Resolution', 'მეიჯარე-მოიჯარეს დავის მოგვარება', 'Guidance and representation for resolving disputes over deposits, repairs, or lease terms between landlords and tenants.', 'კონსულტაცია და წარმომადგენლობა დეპოზიტების, შეკეთებების ან იჯარის პირობებთან დაკავშირებული დავების მოსაგვარებლად მეიჯარესა და მოიჯარეს შორის.', 500, 'GEL', null, false, '{}', '{}', '[]'::jsonb, '[]'::jsonb, 13),
  ('citizenship-application-assistance', (select id from public.categories where slug = 'immigration'), (select id from public.lawyers where slug = 'ana-kapanadze'), 'Citizenship Application Assistance', 'მოქალაქეობის განაცხადის მხარდაჭერა', 'Complete support through the citizenship application process, from eligibility review to document submission.', 'სრული მხარდაჭერა მოქალაქეობის განაცხადის პროცესში, უფლებამოსილების შემოწმებიდან დოკუმენტების წარდგენამდე.', 800, 'GEL', null, false, '{}', '{}', '[]'::jsonb, '[]'::jsonb, 14),
  ('prenuptial-agreement-drafting', (select id from public.categories where slug = 'family'), (select id from public.lawyers where slug = 'giorgi-abashidze'), 'Prenuptial Agreement Drafting', 'საქორწინო კონტრაქტის შედგენა', 'A clear, fair prenuptial agreement drafted to protect both partners'' interests before marriage.', 'ნათელი და სამართლიანი საქორწინო კონტრაქტის შედგენა, რომელიც დაიცავს ორივე პარტნიორის ინტერესებს ქორწინებამდე.', 450, 'GEL', null, false, '{}', '{}', '[]'::jsonb, '[]'::jsonb, 15)
on conflict (slug) do update set
  category_id = excluded.category_id, lawyer_id = excluded.lawyer_id, title_en = excluded.title_en,
  title_ka = excluded.title_ka, description_en = excluded.description_en, description_ka = excluded.description_ka,
  price = excluded.price, duration_minutes = excluded.duration_minutes, popular = excluded.popular,
  includes_en = excluded.includes_en, includes_ka = excluded.includes_ka, faq_en = excluded.faq_en,
  faq_ka = excluded.faq_ka, sort_order = excluded.sort_order;

-- Reviews ----------------------------------------------------------------
delete from public.reviews;
insert into public.reviews (author_name, author_role_en, author_role_ka, rating, quote_en, quote_ka, service_id, lawyer_id, featured, sort_order) values
  ('Mikheil T.', 'Small Business Owner', 'მცირე ბიზნესის მფლობელი', 5, 'Law Market connected me with an amazing lawyer who handled my LLC formation quickly and professionally. Everything was transparent from the first message.', 'Law Market-მა დამაკავშირა შესანიშნავ იურისტთან, რომელმაც ჩემი შპს-ს დაფუძნება სწრაფად და პროფესიონალურად გააკეთა. ყველაფერი გამჭვირვალე იყო პირველივე შეტყობინებიდან.', (select id from public.services where slug = 'llc-formation'), (select id from public.lawyers where slug = 'nino-beridze'), true, 0),
  ('Priya S.', 'Entrepreneur', 'მეწარმე', 5, 'Transparent pricing, great communication, and real results. I highly recommend Law Market to anyone who needs a contract reviewed properly.', 'გამჭვირვალე ფასები, შესანიშნავი კომუნიკაცია და რეალური შედეგები. მე ვურჩევდი Law Market-ს ყველას, ვისაც ხელშეკრულების სათანადოდ შემოწმება სჭირდება.', (select id from public.services where slug = 'contract-review'), (select id from public.lawyers where slug = 'mariam-chkheidze'), false, 1),
  ('James W.', 'Startup Founder', 'სტარტაპის დამფუძნებელი', 5, 'I found the right lawyer for my business in less than 24 hours. Incredible experience from search to booking.', 'ჩემი ბიზნესისთვის შესაფერისი იურისტი 24 საათზე ნაკლებ დროში ვიპოვე. დაუჯერებელი გამოცდილება ძებნიდან დაჯავშნამდე.', (select id from public.services where slug = 'trademark-registration'), (select id from public.lawyers where slug = 'nino-beridze'), false, 2),
  ('Elene Gogia', 'Client', 'კლიენტი', 5, 'Giorgi handled a very difficult time in my life with patience and genuine care. I always knew what was happening with my case.', 'გიორგიმ ჩემი ცხოვრების ძალიან რთული პერიოდი მოთმინებითა და გულწრფელი ზრუნვით გაუძღვა. ყოველთვის ვიცოდი, რა ხდებოდა ჩემს საქმეში.', (select id from public.services where slug = 'divorce-filing'), (select id from public.lawyers where slug = 'giorgi-abashidze'), false, 3),
  ('Thomas Berg', 'Remote Worker, relocated to Georgia', 'დისტანციური მუშაკი, გადმოსახლდა საქართველოში', 5, 'As a foreigner navigating residence permits for the first time, having Ana explain every step in plain English made all the difference.', 'როგორც უცხოელისთვის, რომელიც პირველად აწყდებოდა ბინადრობის ნებართვის საკითხს, ანას მიერ ყოველი ნაბიჯის მარტივად ახსნამ დიდი განსხვავება შექმნა.', (select id from public.services where slug = 'visa-residence-permit-filing'), (select id from public.lawyers where slug = 'ana-kapanadze'), false, 4),
  ('Sopho Kiladze', 'First-time Homebuyer', 'პირველად ბინის მყიდველი', 4, 'Levan caught an issue in the property title that I would have completely missed. Worth every lari for the peace of mind.', 'ლევანმა შენიშნა პრობლემა ქონების საკუთრებაში, რომელსაც მე საერთოდ ვერ შევამჩნევდი. ღირდა ყოველი გადახდილი ლარი სულის სიმშვიდისთვის.', (select id from public.services where slug = 'property-purchase-agreement-review'), (select id from public.lawyers where slug = 'levan-tsereteli'), false, 5);

-- Editable site copy -----------------------------------------------------
insert into public.site_content (key, value_en, value_ka, description) values
  ('hero.title', 'Legal help at a fixed price', 'იურიდიული დახმარება ფიქსირებული ფასით', 'Homepage hero headline'),
  ('hero.subtitle', 'Find verified lawyers, compare services, and book with a satisfaction guarantee.', 'იპოვეთ იურისტები, შეადარეთ სერვისები და დაჯავშნეთ კმაყოფილების გარანტიით.', 'Homepage hero subtitle'),
  ('banner.text', 'Free 15-minute consultation on every service', '15-წუთიანი უფასო კონსულტაცია ყოველ სერვისზე', 'Sitewide top banner'),
  ('guarantee.title', 'Every service is covered by our satisfaction guarantee', 'ყველა სერვისი დაფარულია კმაყოფილების გარანტიით', 'Guarantee band heading')
on conflict (key) do nothing;

